language: go
os:
  - linux
go:
  - 1.8.1
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - go get -t -v ./...
  - go test ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
after_success:
  - go build -o blank-queue-linux-amd64 -ldflags "-X main.buildTime=`date +%Y-%m-%d:%H:%M:%S` -X main.gitHash=`git rev-parse --short HEAD`"
  - GOOS=darwin GOARCH=amd64 go build -o blank-queue-darwin-amd64 -ldflags "-X main.buildTime=`date +%Y-%m-%d:%H:%M:%S` -X main.gitHash=`git rev-parse --short HEAD`"
  - GOOS=windows GOARCH=amd64 go build -o blank-queue-win32-amd64.exe -ldflags "-X main.buildTime=`date +%Y-%m-%d:%H:%M:%S` -X main.gitHash=`git rev-parse --short HEAD`"

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file:
    - blank-queue-linux-amd64
    - blank-queue-darwin-amd64
    - blank-queue-win32-amd64.exe
  skip_cleanup: true
  on:
    tags: true